name: Push to Master

on:
  push:
    tags:
      - "v*.*.*" # Matches any tag that starts with 'v' and follows semantic versioning
      - "v*.*.*-ent*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: CI
        env:
          CROSS: "true"
        run: make ci
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REPO || github.repository }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build to Dockerhub
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: package/Dockerfile
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
      - name: checksum
        run: |
          cd dist/artifacts
          sha256sum ./* > sha256sum.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/artifacts/*"
          draft: true
